config/routes.rb
Rails.application.routes.draw do
  root "auth/login#new"

  namespace :auth do
    get "/register", to: "register#new"
    post "/register", to: "register#create"
    get "/login", to: "login#new"
    post "/login", to: "login#create"
    post "/logout", to: "logout#destroy"
  end
  
  namespace :app do
    get "/", to: "dashboard#index", as: "dashboard"
    resources :categories
    resources :tags
    resources :blogs
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
  def formatted_created_at
    created_at.strftime('%d-%m-%Y %H:%M')
  end

  private

  def generate_slug
    self.slug = defined?(name) ?  name.parameterize : title.parameterize
  end
end

app/models/blog.rb
class Blog < ApplicationRecord
    before_save :generate_slug
    before_destroy :delete_attached_image
    belongs_to :user, foreign_key: :user_id
    belongs_to :category, foreign_key: :category_id
    has_many :blogs_tags, dependent: :destroy
    has_many :tags, through: :blogs_tags
    has_one_attached :image
    accepts_nested_attributes_for :tags, allow_destroy: true
    validates :title, presence: true, uniqueness: true
    validates :slug, uniqueness: true, allow_blank: true
    validates :content, presence: true
    validates :category_id, presence: true
    validate :acceptable_image

    private

    def acceptable_image
        return unless image.attached?
      
        acceptable_types = ["image/jpeg", "image/png"]
        unless acceptable_types.include?(image.content_type)
          errors.add(:image, "must be a JPEG or PNG")
        end
    end

    def delete_attached_image
      image.purge if image.attached?
    end
end

app/models/blog_tag.rb
class BlogTag < ApplicationRecord
    self.table_name = "blogs_tags"
    belongs_to :blog
    belongs_to :tag
end

app/models/category.rb
class Category < ApplicationRecord
    before_save :generate_slug
    has_many :blogs, foreign_key: :category_id, dependent: :destroy
    validates :name, presence: true, uniqueness: true
    validates :slug, uniqueness: true, allow_blank: true
end

app/models/image.rb
class Image < ApplicationRecord
    belongs_to :blog, foreign_key: :blog_id
    validates :url, presence: true
end

app/models/tag.rb
class Tag < ApplicationRecord
    before_save :generate_slug
    has_many :blogs_tags
    has_many :blogs, through: :blogs_tags
    validates :name, presence: true, uniqueness: true
    validates :slug, uniqueness: true, allow_blank: true
end

app/models/user.rb
class User < ApplicationRecord
    has_many :blogs, foreign_key: :user_id, dependent: :destroy
    validates :username, presence: true, length: { minimum: 2 }
    validates :email, presence: true, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP }
    validates :password, presence: true, length: { in: 6..30 }, confirmation: true
end

app/controllers/app/blogs_controller.rb
module App
    class BlogsController < ApplicationController
        before_action :guest
        before_action :set_blog, only: [:show, :edit, :update, :destroy]

        def index
            @blogs = @authenticated_user.blogs().eager_load(:category).all
        end

        def new
            @blog = Blog.new
        end

        def create
            @blog = authenticated_user.blogs().new(blog_params)
            if @blog.save
                redirect_to new_app_blog_path, success: "Le blog est créé avec succès !!"
            else
                render :new, status: :unprocessable_entity
            end
        end

        def show
        end

        def edit
        end

        def update
            @blog.update(blog_params)
            redirect_to edit_app_blog_path, success: "Le blog est modifié avec succès !!"
        end

        def destroy
            @blog.destroy
            redirect_to app_blogs_path, status: :see_other
        end

        private

        def blog_params
            params.require(:blog).permit(:title, :content, :category_id, :user_id, :image, blog_tags_attributes: [:id, :tag_id, :_destroy])
        end

        def set_blog
            @blog = Blog.find(params[:id])
        end
    end
end

app/controllers/app/categories_controller.rb
module App
    class CategoriesController < ApplicationController
        before_action :guest
        before_action :set_category, only: [:show, :edit, :update, :destroy]
        
        def index
            @categories = Category.all
        end
        
        def new
            @category = Category.new
        end

        def create
            @category = Category.new(category_params)
            if @category.save
                redirect_to new_app_category_path, success: "La catégorie est ajoutée avec succès !!"
            else
                render :new, status: :unprocessable_entity
            end
        end

        def show
        end

        def edit
        end

        def update
            @category.update(category_params)
            redirect_to edit_app_category_path, success: "La catégorie est modifiée avec succès !!"
        end

        def destroy
            @category.destroy
            redirect_to app_categories_path, status: :see_other
        end

        private

        def category_params
            params.require(:category).permit(:name)
        end

        def set_category
            @category = Category.find(params[:id])
        end

    end
end

app/controllers/app/dashboard_controller.rb
module App
    class DashboardController < ApplicationController
        before_action :guest
        def index
        end
    end
end

app/controllers/app/tags_controller.rb
module App
    class TagsController < ApplicationController
        before_action :guest
        before_action :set_tag, only: [:show, :edit, :update, :destroy]
        
        def index
            @tags = Tag.order(id: :desc)
        end

        def new
            @tag = Tag.new
        end

        def create
            @tag = Tag.new(tag_params)
            if @tag.save
                redirect_to new_app_tag_path, success: "Tag is added successfully !!"
            end
        end

        def show
        end

        def edit
        end

        def update
            @tag.update(tag_params)
            redirect_to edit_app_tag_path, success: "Tag is updated successfully !!"
        end

        def destroy
            @tag.destroy
            redirect_to app_tags_path
        end
        
        private

        def tag_params
            params.require(:tag).permit(:name)
        end

        def set_tag
            @tag = Tag.find(params[:id])
        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    add_flash_types :success, :danger, :warning
    helper_method :authenticated_user
    protect_from_forgery with: :exception

    def authenticated_user
        @authenticated_user ||= User.find_by(id: session[:user_id])
    end

    def authenticated
        if authenticated_user
            redirect_to app_dashboard_path
        end
    end

    def guest
        if !authenticated_user
            redirect_to auth_login_path
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/app/blogs/_form.html.erb
<%= form_for @blog, url: local_assigns[:url], html: { multipart: true } do |f| %>
    <div class="form-group">
        <%= f.label :title, "Titre" %>
        <%= f.text_field :title, class: "form-control" %>
        <% if @blog.errors[:title].any? %>
            <span class="text-danger"><%= @blog.errors[:title].first %></span>
        <% end %>
    </div>
    <div class="form-group">
        <%= f.label :category_id, "Categorie" %>
        <%= f.select :category_id, Category.all.map{|c| [c.name, c.id]}, {}, class: "form-control" %>
        <% if @blog.errors[:category_id].any? %>
            <span class="text-danger"><%= @blog.errors[:category_id].first %></span>
        <% end %>
    </div>

    <div class="form-group">
        <%= f.label :image, "Image" %>
        <%= f.file_field :image, class: "form-control" %>
        <% if @blog.errors.has_key?(:image) %>
            <span class="text-danger"><%= @blog.errors[:image].join(', ') %></span>
        <% end %>
    </div>
    
    <div class="form-group">
        <%= f.label :content, "Content" %>
        <%= f.text_area :content, class: "form-control h-100", :rows => 10 %>
        <% if @blog.errors[:content].any? %>
            <span class="text-danger"><%= @blog.errors[:content].first %></span>
        <% end %>
    </div>

    <div class="form-group">
        <%= f.label :tags %>
        <%= f.collection_check_boxes(:tag_id, Tag.all, :id, :name, { checked: @blog.tag_ids }) do |cb| %>
      <div class="form-check">
        <%= cb.check_box(class: 'form-check-input') %>
        <%= cb.label(class: 'form-check-label') %>
      </div>
    <% end %>
    </div>

    <div class="form-group">
        <%= f.submit local_assigns[:name], class: "btn btn-primary btn-lg btn-block" %>
    </div>
<% end %>

app/views/app/blogs/edit.html.erb
<section class="section">
    <div class="section-header">
        <h1>Blogs</h1>
        <div class="section-header-breadcrumb">
            <div class="breadcrumb-item active"><a href="<%= app_dashboard_path %>">Dashboard</a></div>
            <div class="breadcrumb-item"><a href="<%= app_blogs_path %>">Blogs</a></div>
            <div class="breadcrumb-item">Modifier</div>
        </div>
    </div>
    <div class="section-body">
        <div class="col-12">
            <% if flash[:success] %>
                <div class="alert alert-success">
                    <%= flash[:success] %>
                </div>
            <% end %>
            <div class="card">
                <div class="card-body">
                    <%= render partial: "form", locals: { name: "Modifier", url: app_blog_path } %>
                </div>
            </div>
        </div>
    </div>
</section>

app/views/app/blogs/index.html.erb
<section class="section">
    <div class="section-header">
        <h1>Blogs </h1><a class="text-sm ml-3 btn btn-success" href="<%= new_app_blog_path %>">+</a>  
        <div class="section-header-breadcrumb">
            <div class="breadcrumb-item active"><a href="<%= app_dashboard_path %>">Dashboard</a></div>
            <div class="breadcrumb-item">Blogs</div>
        </div>
    </div>
    <div class="section-body">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-bordered table-md">
                            <tbody>
                                <tr>
                                    <th>Titre</th>
                                    <th>Categorie</th>
                                    <th>Créé le</th>
                                    <th>Action</th>
                                </tr>
                                <% @blogs.each do |b| %>
                                    <tr>
                                        <td><%= b.title %></td>
                                        <td><%= b.category.name %></td>
                                        <td><%= b.formatted_created_at %></td>
                                        <td class="d-flex">
                                            <a href="<%= app_blog_path(b.id) %>" class="btn btn-info btn-sm">Détail</a>
                                            <a href="<%= edit_app_blog_path(b.id) %>" class="btn btn-warning btn-sm mx-2">Modifier</a>
                                            <%= button_to  "Supprimer", app_blog_path(b), method: :delete, data: { turbo_method: :delete, turbo_confirm: "Vous êtes sûr ?" }, class: "btn btn-danger btn-sm"%>
                                        </td>
                                    </tr>
                                <% end %>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

app/views/app/blogs/new.html.erb
<section class="section">
    <div class="section-header">
        <h1>Blogs</h1>
        <div class="section-header-breadcrumb">
            <div class="breadcrumb-item active"><a href="<%= app_dashboard_path %>">Dashboard</a></div>
            <div class="breadcrumb-item"><a href="<%= app_blogs_path %>">Blogs</a></div>
            <div class="breadcrumb-item">Créé</div>
        </div>
    </div>
    <div class="section-body">
        <div class="col-12">
            <% if flash[:success] %>
                <div class="alert alert-success">
                    <%= flash[:success] %>
                </div>
            <% end %>
            <div class="card">
                <div class="card-body">
                    <%= render partial: "form", locals: { name: "Ajouter", url: app_blogs_path } %>
                </div>
            </div>
        </div>
    </div>
</section>

app/views/app/blogs/show.html.erb
<section class="section">
    <div class="section-header">
        <h1>Blogs</h1>
        <div class="section-header-breadcrumb">
            <div class="breadcrumb-item active"><a href="<%= app_dashboard_path %>">Dashboard</a></div>
            <div class="breadcrumb-item"><a href="<%= app_blogs_path %>">Blogs</a></div>
            <div class="breadcrumb-item">Détail</div>
        </div>
    </div>
    <div class="section-body">
        <div class="col-12">
            <div class="card">
                <% if @blog.image.attached? %>
                    <%= image_tag @blog.image, class: "card-img-top", style: "height: 400px", alt: @blog.title %>
                <% end %>
                <div class="card-body">
                    <h1><%= @blog.title %></h1>
                    <hr/>
                    <p><%= @blog.content %></p>
                    <hr>
                    <p>Le <b><%= @blog.formatted_created_at %></b></p>
                </div>
            </div>
        </div>
    </div>
</section>

app/views/app/categories/_form.html.erb
<%= form_for @category, url: local_assigns[:url] do |f| %>
    <div class="form-group">
        <%= f.label :name, "Nom" %>
        <%= f.text_field :name, class: "form-control" %>
        <% if @category.errors[:name].any? %>
            <span class="text-danger"><%= @category.errors[:name].first %></span>
        <% end %>
    </div>
    <div class="form-group">
        <%= f.submit local_assigns[:name], class: "btn btn-info btn-lg btn-block" %>
    </div>
<% end %>

app/views/app/categories/edit.html.erb
<section class="section">
    <div class="section-header">
        <h1>Categories</h1>
        <div class="section-header-breadcrumb">
            <div class="breadcrumb-item active"><a href="<%= app_dashboard_path %>">Dashboard</a></div>
            <div class="breadcrumb-item"><a href="<%= app_categories_path %>">Categories</a></div>
            <div class="breadcrumb-item">Modifier</div>
        </div>
    </div>
    <div class="section-body">
        <div class="col-12">
            <% if flash[:success] %>
                <div class="alert alert-success">
                    <%= flash[:success] %>
                </div>
            <% end %>
            <div class="card">
                <div class="card-body">
                    <%= render partial: "form", locals: { name: "Modifier", url: app_category_path(@category.id) } %>
                </div>
            </div>
        </div>
    </div>
</section>

app/views/app/categories/index.html.erb
<section class="section">
    <div class="section-header">
        <h1>Categories </h1><a class="text-sm ml-3 btn btn-success" href="<%= new_app_category_path %>">+</a>  
        <div class="section-header-breadcrumb">
            <div class="breadcrumb-item active"><a href="<%= app_dashboard_path %>">Dashboard</a></div>
            <div class="breadcrumb-item">Categories</div>
        </div>
    </div>
    <div class="section-body">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-bordered table-md">
                            <tbody>
                                <tr>
                                    <th>Nom</th>
                                    <th>Créé le</th>
                                    <th>Action</th>
                                </tr>
                                <% @categories.each do |c| %>
                                    <tr id="category-<%= c.id %>">
                                        <td><%= c.name %></td>
                                        <td><%= c.formatted_created_at %></td>
                                        <td class="d-flex">
                                            <a href="<%= edit_app_category_path(c.id) %>" class="btn btn-warning btn-sm mr-2">Modifier</a>
                                            <form id="delete_category_form_<%= c.id %>" action="<%= app_category_path(c) %>" method="POST">
                                                <input type="hidden" name="_method" value="DELETE">
                                                <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
                                                <button type="submit" class="btn btn-danger btn-sm btn_delete_category" data-count="<%= c.blogs.count() %>" data-id="<%= c.id %>" >Supprimer</button>
                                            </form>
                                        </td>
                                    </tr>
                                <% end %>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<script type="text/javascript">
    $(".btn_delete_category").on("click", function(event) {
        event.preventDefault();
        const id = $(this).data("id");
        const count = $(this).data("count");
        if ( count == 0 || confirm("La catégorie est dèja utilisé, voulez vous supprimer (la catégorie et les blogs liées) ? ") ) {
            $(`#delete_category_form_${id}`).submit();
        }
    });
</script>

app/views/app/categories/new.html.erb
<section class="section">
    <div class="section-header">
        <h1>Categories</h1>
        <div class="section-header-breadcrumb">
            <div class="breadcrumb-item active"><a href="<%= app_dashboard_path %>">Dashboard</a></div>
            <div class="breadcrumb-item"><a href="<%= app_categories_path %>">Categories</a></div>
            <div class="breadcrumb-item">Créé</div>
        </div>
    </div>
    <div class="section-body">
        <div class="col-12">
            <% if flash[:success] %>
                <div class="alert alert-success">
                    <%= flash[:success] %>
                </div>
            <% end %>
            <div class="card">
                <div class="card-body">
                    <%= render partial: "form", locals: { name: "Ajouter", url: app_categories_path } %>
                </div>
            </div>
        </div>
    </div>
</section>

app/views/app/dashboard/index.html.erb
<section class="section">
    <div class="section-header">
        <h1>Blank Page</h1>
    </div>

    <div class="section-body">
    </div>
</section>

app/views/app/tags/_form.html.erb
<%= form_for @tag, url: local_assigns[:url] do |f| %>
    <div class="form-group">
        <%= f.label :name, "Nom" %>
        <%= f.text_field :name, class: "form-control" %>
        <% if @tag.errors[:name].any? %>
            <span class="text-danger"><%= @tag.errors[:name].first %></span>
        <% end %>
    </div>
    <div class="form-group">
        <%= f.submit local_assigns[:name], class: "btn btn-info btn-lg btn-block" %>
    </div>
<% end %>

app/views/app/tags/edit.html.erb
<section class="section">
    <div class="section-header">
        <h1>Tags</h1>
        <div class="section-header-breadcrumb">
            <div class="breadcrumb-item active"><a href="<%= app_dashboard_path %>">Dashboard</a></div>
            <div class="breadcrumb-item"><a href="<%= app_tags_path %>">Tags</a></div>
            <div class="breadcrumb-item">Modifier</div>
        </div>
    </div>
    <div class="section-body">
        <div class="col-12">
            <% if flash[:success] %>
                <div class="alert alert-success">
                    <%= flash[:success] %>
                </div>
            <% end %>
            <div class="card">
                <div class="card-body">
                    <%= render partial: "form", locals: { name: "Modifier", url: app_tag_path(@tag.id) } %>
                </div>
            </div>
        </div>
    </div>
</section>

app/views/app/tags/index.html.erb
<section class="section">
    <div class="section-header">
        <h1>Tags </h1><a class="text-sm ml-3 btn btn-success" href="<%= new_app_tag_path %>">+</a>  
        <div class="section-header-breadcrumb">
            <div class="breadcrumb-item active"><a href="<%= app_dashboard_path %>">Dashboard</a></div>
            <div class="breadcrumb-item">Tags</div>
        </div>
    </div>
    <div class="section-body">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-bordered table-md">
                            <tbody>
                                <tr>
                                    <th>Nom</th>
                                    <th>Créé le</th>
                                    <th>Action</th>
                                </tr>
                                <% @tags.each do |t| %>
                                    <tr id="tag-<%= t.id %>">
                                        <td><%= t.name %></td>
                                        <td><%= t.formatted_created_at %></td>
                                        <td class="d-flex">
                                            <a href="<%= edit_app_tag_path(t.id) %>" class="btn btn-warning btn-sm mr-2">Modifier</a>
                                            <%= button_to "Delete", app_tag_path(t), method: :delete, class: "btn btn-danger btn-sm" %>
                                        </td>
                                    </tr>
                                <% end %>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<script type="text/javascript">
    $(".btn_delete_category").on("click", function(event) {
        event.preventDefault();
        const id = $(this).data("id");
        const count = $(this).data("count");
        if ( count == 0 || confirm("La catégorie est dèja utilisé, voulez vous supprimer (la catégorie et les blogs liées) ? ") ) {
            $(`#delete_category_form_${id}`).submit();
        }
    });
</script>

app/views/app/tags/new.html.erb
<section class="section">
    <div class="section-header">
        <h1>Tags</h1>
        <div class="section-header-breadcrumb">
            <div class="breadcrumb-item active"><a href="<%= app_dashboard_path %>">Dashboard</a></div>
            <div class="breadcrumb-item"><a href="<%= app_tags_path %>">Tags</a></div>
            <div class="breadcrumb-item">Créé</div>
        </div>
    </div>
    <div class="section-body">
        <div class="col-12">
            <% if flash[:success] %>
                <div class="alert alert-success">
                    <%= flash[:success] %>
                </div>
            <% end %>
            <div class="card">
                <div class="card-body">
                    <%= render partial: "form", locals: { name: "Ajouter", url: app_tags_path } %>
                </div>
            </div>
        </div>
    </div>
</section>

app/views/layouts/application.html.erb
<%= render partial: "partials/header" %>

    <div id="app">
      <div class="main-wrapper main-wrapper-1">
          <div class="navbar-bg"></div>
          <nav class="navbar navbar-expand-lg main-navbar">
              <div class="mr-auto">
                  <ul class="navbar-nav mr-3">
                      <li>
                        <a href="#" data-toggle="sidebar" class="nav-link nav-link-lg">
                          <i class="fas fa-bars"></i>
                        </a>
                      </li>
                  </ul>
              </div>
              <ul class="navbar-nav navbar-right">
                  <li class="dropdown">
                      <a href="#" data-toggle="dropdown" class="nav-link dropdown-toggle nav-link-lg nav-link-user">
                          <%= image_tag "avatar-1.png", class: "rounded-circle mr-1" %>
                          <div class="d-sm-none d-lg-inline-block">Hi, <%= authenticated_user.username %></div>
                      </a>
                      <div class="dropdown-menu dropdown-menu-right">
                          <div class="dropdown-title">Logged in 5 min ago</div>
                          <a href="features-profile.html" class="dropdown-item has-icon">
                              <i class="far fa-user"></i> Profile
                          </a>
                          <a href="features-activities.html" class="dropdown-item has-icon">
                              <i class="fas fa-bolt"></i> Activities
                          </a>
                          <a href="features-settings.html" class="dropdown-item has-icon">
                              <i class="fas fa-cog"></i> Settings
                          </a>
                          <div class="dropdown-divider"></div>
                          <form action="<%= auth_logout_path %>" method="POST">
                                <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
                                <button type="submit" class="dropdown-item has-icon text-danger logout-button d-flex align-items-center">
                                    <i class="fas fa-sign-out-alt"></i> Logout
                                </button>
                          </form>
                      </div>
                  </li>
              </ul>
          </nav>
          <div class="main-sidebar sidebar-style-2">
              <aside id="sidebar-wrapper">
                  <div class="sidebar-brand">
                      <a href="index.html">Stisla</a>
                  </div>
                  <div class="sidebar-brand sidebar-brand-sm">
                      <a href="index.html">St</a>
                  </div>
                  <ul class="sidebar-menu">
                      <li class="<%= 'active' if controller_name == 'dashboard' %>">
                          <a class="nav-link" href="<%= app_dashboard_path %>">
                              <i class="fa-solid fa-house"></i> <span>Dashboard</span>
                          </a>
                      </li>
                      <li class="<%= 'active' if controller_name === 'categories' %>">
                          <a class="nav-link" href="<%= app_categories_path %>">
                              <i class="fa-solid fa-calendar-days"></i> <span>Categories</span>
                          </a>
                      </li>
                      <li class="<%= 'active' if controller_name === "tags" %>">
                          <a class="nav-link" href="<%= app_tags_path %>">
                              <i class="fa-solid fa-tags"></i> <span>Tags</span>
                          </a>
                      </li>
                      <li class="<%= 'active' if controller_name === "blogs" %>">
                          <a class="nav-link" href="<%= app_blogs_path %>">
                              <i class="fa-brands fa-blogger"></i> <span>Blogs</span>
                          </a>
                      </li>
                  </ul>

              </aside>
          </div>

        <!-- Main Content -->
        <div class="main-content">
          <%= yield %>
        </div>
        <footer class="main-footer">
          <div class="footer-left">
              Copyright &copy; 2023 <div class="bullet"></div> By <a href="https://github.com/ayoub11599/blograils">Ayoub Boumahra</a>
          </div>
        </footer>
      </div>
    </div>
    
<%= render partial: "partials/footer" %>

app/views/layouts/auth_layout.html.erb
<%= render partial: "partials/header" %>
    <div class="container py-5">
        <div id="app">
            <section class="section">
                <div class="container mt-5">
                    <div class="row">
                        <div class="col-12 col-sm-10 offset-sm-1 col-md-8 offset-md-2 col-lg-8 offset-lg-2 col-xl-8 offset-xl-2">
                            <% flash.each do |name, val| %>
                                <% puts name %>
                                <div class="alert alert-<%= name %>">
                                    <%= val %>
                                </div>
                            <% end %>
                            <div class="card card-primary">
                                <div class="card-header">
                                    <h4>
                                        <%= @is_login_page ? "Se connecter" : "Registre" %>
                                    </h4>
                                </div>
                                <div class="card-body">
                                    <%= yield %>
                                </div>
                            </div>
                            <div class="text-muted text-center">
                                <% if @is_login_page %>
                                    Vous n'avez pas de compte ? <a href="<%= auth_register_path %>">Créer un</a>
                                <% else %>
                                    Vous avez dèja un compte ? <a href="<%= auth_login_path %>">Se connecter</a>
                                <% end %>
                            </div>
                            <div class="simple-footer">
                                Copyright &copy; Ayoub Boumahra 2023
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </div>
<%= render partial: "partials/footer" %>

app/views/login/new.html.erb
<%= form_tag "/login", method: :post do %>
    <div class="form-group">
        <%= label_tag :email, "Adress email", class: "control-label" %>
        <%= text_field_tag :email, nil, class: "form-control" %>
    </div>

    <div class="form-group">
        <%= label_tag :password, "Mot de passe", class: "control-label" %>
        <%= password_field_tag :password, nil, class: "form-control" %>
    </div>

    <div class="form-group">
        <%= submit_tag "S'inscrire", class: "btn btn-primary btn-lg btn-block" %>
    </div>
<% end %>

app/views/partials/_footer.html.erb
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js"></script>
    <%= javascript_include_tag 'nice_scroll' %>
    <%= javascript_include_tag 'stisla' %>
    <%= javascript_include_tag 'scripts' %>
    <%= javascript_include_tag "custom" %>
  </body>
</html>